routes.py
#----routes done as a blueprint for further expansion --

from flask import Blueprint, render_template,request,session, redirect, url_for, jsonify
from db import db  # Import the db instance
from sqlalchemy import text, select, bindparam
import pandas as pd
from markupsafe import Markup
import json
import plotly
import plotly.express as px
import plotly.graph_objects as go

main = Blueprint('main',__name__)
@main.route('/')
@main.route("/index/")
def index():
    return render_template('index.html')

#-----------------------------------------------------------------------------------------------------------------------------
##DASHBOARD ROUTES
@main.route('/dashboard/', methods=['GET'])
def dash():
    invoice_info = fetch_invoice()
    loc_info = fetch_coords()
    return render_template('dashboard.html', invoices=invoice_info,coords=loc_info)

def fetch_invoice():
    invoices = []
    sql = text("CALL random_invoice()")
    result = db.session.execute(sql)
    for row in result.mappings():
        invoices.append(row)
    return invoices

def fetch_coords():
    coords = []
    sql = text("CALL random_ports()")
    result = db.session.execute(sql)
    for row in result:
        coords.append(row._asdict())
    return coords

@main.route('/dashboard/orders', methods=['GET'])
def notification():
    results_set = []
    sql = text("CALL random_invoice()")
    result = db.session.execute(sql)
    for row in result.mappings():
        results_set.append(row)
    return jsonify(results_set)
#-----------------------------------------------------------------------------------------------------------------------------
##TRACKING ROUTES
@main.route('/search/', methods=['GET'])
def search():
    return render_template('search.html')

@main.route('/search/api/tracking/', methods=['GET'])
def tracking_search():
    track_id = request.args.get('tracking')
    if not track_id:
        return render_template('_tracking_cards.html',results=[])
    sql_query = text("CALL tracking_lookup(:track_id)")
    result = db.session.execute(sql_query,{"track_id":track_id})
    results = [row._asdict() for row in result.fetchall()]
    return render_template('_tracking_cards.html', results=results)

@main.route('/search/api/tracking/<string:trackingno>', methods=['GET'])
def full_tracking(trackingno):
    sql = text("CALL full_tracking_lookup(:trackingno_param)")
    result = db.session.execute(sql,{"trackingno_param":trackingno})
    tracking_details = [row._asdict() for row in result.fetchall()]
    return render_template('_full_tracking.html', tracking_details=tracking_details[0] if tracking_details else None)
    
#-----------------------------------------------------------------------------------------------------------------------------
##INVOICE ROUTES
@main.route('/search/api/invoice/', methods=['GET'])
def invoice_search():
    inv_id = request.args.get('invoice')
    if not inv_id:
        return render_template('_invoice_cards.html',results=[])
    sql_search = text("CALL invoice_lookup(:inv_id)")
    result = db.session.execute(sql_search,{"inv_id":inv_id})
    results = [row._asdict() for row in result.fetchall()]
    return render_template('_invoice_cards.html', results=results)

@main.route('/search/api/invoice/<string:invoiceno>', methods=['GET'])
def full_invoice(invoiceno):
    sql_search = text("CALL invoice_lookup(:invoice_id_param)")
    result = db.session.execute(sql_search,{"invoice_id_param":invoiceno})
    invoice_details = [row._asdict() for row in result.fetchall()]
    return render_template('_full_invoice.html', invoice_details=invoice_details[0] if invoice_details else None)
    

#-----------------------------------------------------------------------------------------------------------------------------
#QUOTE ROUTES
@main.route('/shopping/', methods=['GET'])
def quote_load():
    inventory = text('CALL inventory_menus')
    inv_items = db.session.execute(text(inventory))
    inv_menu = [row._asdict() for row in inv_items]
    location = text('CALL loc_menus')
    loc_items = db.session.execute(text(location))
    loc_menu = [row._asdict() for row in loc_items.fetchall()]
    return render_template('shopping.html',inv=inv_menu,loc=loc_menu)

@main.route('/shopping/api/city/<string:country_name>', methods=['GET'])
def cities(country_name):
    city_match = text("CALL port_city_match(:country_param)")
    city_loc = db.session.execute(city_match,{"country_param":country_name})
    city_list = [row._asdict() for row in city_loc.fetchall()]
    return jsonify(city_list)

@main.route('/shopping/api/products/<string:prod_name>', methods=['GET'])
def product_search(prod_name):
    product_type = text("CALL product_typeload(:prod_name)")
    names = db.session.execute(product_type,{"prod_name":prod_name})
    name_list = [row._asdict() for row in names.fetchall()]
    return jsonify(name_list)

@main.route('/shopping/api/containers/<string:prod_name>/<string:prod_type>', methods=['GET'])
def shipping_containers(prod_name,prod_type):
    product_container = text("CALL shipping_containers(:prod_name, :prod_type)")
    types = db.session.execute(product_container,{"prod_name":prod_name,"prod_type":prod_type})
    type_list = [row._asdict() for row in types.fetchall()]
    return jsonify(type_list)

@main.route('/shopping/api/fees/<string:country_name>/<string:city_name>', methods=['GET'])
def addtl_fees(country_name,city_name):
    fees = text("CALL taxes_fees(:country_name, :city_name)")
    regions = db.session.execute(fees,{"country_name":country_name,"city_name":city_name})
    region_list = [row._asdict() for row in regions.fetchall()]
    return jsonify(region_list)



#-----------------------------------------------------------------------------------------------------------------------------
##Employee Routes
@main.route('/employees', methods=['GET'])
def employees():
    return render_template('employees.html')

@main.route('/employees/api/search/', methods=['GET'])
def emp_search():
    emp_no = request.args.get("employee")
    if not emp_no:
        return jsonify([])
    emp_id = text("CALL employee_lookup(:employee_param)")
    staff_query = db.session.execute(emp_id,{"employee_param":emp_no})
    emp_list = [row._asdict() for row in staff_query.fetchall()]
    return render_template('_emp_card.html',emp_list=emp_list)


#-----------------------------------------------------------------------------------------------------------------------------
##REPORTING ROUTES
@main.route('/reports/', methods=['GET', 'POST'])
def report_landing():
    return render_template('reports.html')

@main.route('/reports/sales/', methods=['GET', 'POST'])
def sales_report():
    results_set = []
    sql = text('select * from corpo_sales;')
    result = db.session.execute(sql)
    for row in result.mappings():
        results_set.append(row)
    df = pd.DataFrame(results_set)
    # Create Bar chart
    fig = px.bar(df, x='company_name', y='total_sales')
    # Create graphJSON
    graphJSON = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)     
    # Use render_template to pass graphJSON to html
    return render_template('reports.html', graphJSON=graphJSON)


@main.route('/charts/', methods=['GET', 'POST'])
def myChart():
    results_set = []
    sql = text('select * from shipping_orders ')
    result = db.session.execute(sql)
    for row in result.mappings():
        results_set.append(row)
    df = pd.DataFrame(results_set)   
    # Create Bar chart
    fig = px.bar(df, x='dest_port', y='product_quantity')
    # Create graphJSON
    graphJSON = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)     
    # Use render_template to pass graphJSON to html
    return render_template('charts.html', graphJSON=graphJSON)
    #return render_template('dbquery.html', results=result_html)

#-----------------------------------------------------------------------------------------------------------------------------

@main.route('/db/', methods=['GET'])
def dbQuery():
    results_set = []
    sql = text('select * from shipping_corpos;')
    result = db.session.execute(sql)
    for row in result.mappings():
        results_set.append(row)
    df = pd.DataFrame(results_set)
    result_html = df.to_html(classes='table is-striped')
    result_html = Markup(result_html)
    return render_template('db_page.html', results=result_html)
#error routes
@main.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@main.errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500

templates/_emp_card.html
{% for employee in emp_list %}
<div class="card">
    <header class="card-header">
        <p class="card-header-title">Employee Information</p>
        <button class="card-header-icon" aria-label="more options">
            <span class="icon">
                <i class="fa-solid fa-truck-fast"></i>
            </span>
        </button>
    </header>
    <div class="card-content">
        <div class="content">
            <ul>
                <li>Employee ID:{{ employee['employee_id']}} </li>
                <li>Employee Name: {{employee['fname'] }} {{employee['lname']}}</li>
                <li>Subsidiary: {{employee['subsidiary']}}</li>
                <li>Contract Issued By: {{employee['contracted_by']}}</li>
                <li>Employee Email: {{employee['email']}}</li>
            </ul>
            <br />
        </div>
    </div>
</div>
{% endfor-%}

templates/_full_invoice.html
<!--full invoice panel-->
{% if invoice_details %}
<article class="panel is-primary">
    <p class="panel-heading">Invoice #{{ invoice_details['order_no'] }}</p>
    <button class="delete is-right"></button>
    <a class="panel-block">
        <span class="panel-icon">
            <i class="fas fa-book" aria-hidden="true"></i>
        </span>
        <time datetime="2016-1-1">Ordered on: {{ invoice_details['order_date'] }}</time>
    </a>
    <a class="panel-block">
        <span class="panel-icon">
            <i class="fas fa-book" aria-hidden="true"></i>
        </span>
        Product(s) Ordered: {{invoice_details['product_name']}}
    </a>
    <a class="panel-block">
        <span class="panel-icon">
            <i class="fas fa-book" aria-hidden="true"></i>
        </span>
        Amount: {{invoice_details['product_quantity']}}
    </a>
    <a class="panel-block">
        <span class="panel-icon">
            <i class="fas fa-book" aria-hidden="true"></i>
        </span>
        Shipping from: {{invoice_details['origin']}}
    </a>
    <a class="panel-block">
        <span class="panel-icon">
            <i class="fas fa-book" aria-hidden="true"></i>
        </span>
        Arriving to: {{invoice_details['destination']}}
    </a>
    <a class="panel-block">
        <span class="panel-icon">
            <i class="fas fa-book" aria-hidden="true"></i>
        </span>
        Cost [per invoice_details]: {{invoice_details['price_per_unit']}}
    </a>
    <a class="panel-block">
        <span class="panel-icon">
            <i class="fas fa-book" aria-hidden="true"></i>
        </span>
        Taxes: {{invoice_details['taxes_paid']}}
    </a>
    <a class="panel-block">
        <span class="panel-icon">
            <i class="fas fa-book" aria-hidden="true"></i>
        </span>
        Additional Levies: {{invoice_details['addtl_fees']}}
    </a>
    <a class="panel-block">
        <span class="panel-icon">
            <i class="fas fa-book" aria-hidden="true"></i>
        </span>
        Subtotal: {{invoice_details['subtotal']}}
    </a>
    <a class="panel-block">
        <span class="panel-icon">
            <i class="fas fa-book" aria-hidden="true"></i>
        </span>
        Grand Total: {{invoice_details['total']}}
    </a>

</article>
{% else %}
<p>Invoice details not found.</p>
{% endif %}

templates/_full_tracking.html
<!--full trackingpanel-->
{% if tracking_details %}
<article class="panel is-success">
    <p class="panel-heading">Tracking #{{ tracking_details['tracking_no'] }}</p>
    <button class="delete is-right"></button>
    <a class="panel-block">
        <span class="panel-icon">
            <i class="fas fa-book" aria-hidden="true"></i>
        </span>
        <time datetime="2016-1-1">Ordered on: {{ tracking_details['order_date'] }}</time>
    </a>
    <a class="panel-block">
        <span class="panel-icon">
            <i class="fas fa-book" aria-hidden="true"></i>
        </span>
        Product(s) Ordered: {{tracking_details['product_name']}}
    </a>
    <a class="panel-block">
        <span class="panel-icon">
            <i class="fas fa-book" aria-hidden="true"></i>
        </span>
        Amount: {{tracking_details['product_quantity']}}
    </a>
    <a class="panel-block">
        <span class="panel-icon">
            <i class="fas fa-book" aria-hidden="true"></i>
        </span>
        Shipping from: {{tracking_details['origin_port']}}
    </a>
    <a class="panel-block">
        <span class="panel-icon">
            <i class="fas fa-book" aria-hidden="true"></i>
        </span>
        Arriving to: {{tracking_details['dest_port']}}
    </a>
    <a class="panel-block">
        <span class="panel-icon">
            <i class="fas fa-book" aria-hidden="true"></i>
        </span>
        Estimated Arrival Date: {{tracking_details['est_travel_arr']}}
    </a>
    <a class="panel-block">
        <span class="panel-icon">
            <i class="fas fa-book" aria-hidden="true"></i>
        </span>
        Date Shipped: {{tracking_details['ship_date']}}
    </a>
</article>
{% else %}
<p>Invoice details not found.</p>
{% endif %}

templates/_report_widget.html
{% extends "base.html" %}


{% block title %}Demo Flask{% endblock %}

{% block page_content %}

<body>
    <h1>View Charts</h1>
    <div id='chart' class='chart' ”></div>
</body>


<script type='text/javascript'>
    var graphs = {{ graphJSON | safe}};
    Plotly.plot('chart', graphs, {});
</script>
{% endblock %}

templates/_tracking_cards.html
<div id="trackingcard">
    {% for item in results %}
    <div class="card">
        <header class="card-header">
            <p class="card-header-title">Tracking #{{ item['tracking_no'] }}</p>
            <button class="card-header-icon" aria-label="more options">
                <span class="icon">
                    <i class="fa-solid fa-truck-fast"></i>
                </span>
            </button>
        </header>
        <div class="card-content">
            <div class="content">
                <ul>
                    <li>Shipment Status: {{item['shipment_status']}}</li>
                    <li>Product(s) Ordered: {{item['product_name']}}</li>
                    <li>Amount: {{item['product_quantity']}}</li>
                </ul>
                <br />
                <time datetime="2016-1-1">Ordered on: {{ item['order_date'] }}</time>
            </div>
        </div>
        <footer class="card-footer">
            <a href="#" class="card-footer-item" data-tracking-no="{{ item['tracking_no'] }}" onclick='loadFullTracking("{{ item.tracking_no }}")'>More Details</a>
        </footer>
    </div>
    {% endfor-%}
</div>

templates/base.html
<!DOCTYPE html>
{% block doc -%}
<html{% block html_attribs %}{% endblock html_attribs %}>
    {%- block html %}
    {%- block head %}

    <head>
        {% block title %}<title class="is-centered">Shipping Corpos</title>{% endblock title%}
        {%- block metas %}
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {%- endblock metas %}
        <link rel="shortcut icon" href="{{ url_for('static', filename='haro.ico') }}" type="image">
        <link rel="icon" href="{{ url_for('static', filename='haro.ico') }}" type="image/x-icon">
        {%- block styles %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
        {%- endblock styles %}
        <script src="https://cdn.plot.ly/plotly-3.0.1.min.js" charset="utf-8"></script>
    </head>
    {% endblock head -%}
    <body{% block body_attribs %}{% endblock body_attribs %}>
        {% block body -%}
        {%- block navbar %}
        <nav class="navbar is-dark mb-2" role="navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="/">
                    <img src="{{ url_for('static', filename='logo.png') }}" alt="">
                </a>
                <a role="button" class="navbar-burger" data-target="navslide">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </div>
            <div id="navslide" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" href="/">Home</a>
                    <a class="navbar-item" href="/db/">DBQuery</a>
                    <a class="navbar-item" href="/charts/">Chart</a>
                    <a class="navbar-item" href="/dashboard/">Dashboard</a>
                    <a class="navbar-item" href="/search/">Search</a>
                    <a class="navbar-item" href="/shopping/">Product Calculator</a>
                    <a class="navbar-item" href="/reports/sales">Sales Reporting</a>

                </div>
            </div>
        </nav>
        {% endblock navbar -%}

        {%- block page_content %}
        {% endblock -%}


        {% block scripts %}
        <script src="{{ url_for('static', filename='script.js') }}"></script>
        {% endblock scripts %}

        </body>
        {%- endblock body %}

        </html>
        {%- endblock html %}
        {% endblock doc -%}

templates/charts.html
{% extends "base.html" %}


{% block title %}Demo Flask{% endblock %}

{% block page_content %}

<body>
    <h1>View Charts</h1>
    <div id='chart' class='chart' ”></div>
</body>


<script type='text/javascript'>
    var graphs = {{ graphJSON| safe}};
    Plotly.plot('chart', graphs, {});
</script>
{% endblock %}

templates/dashboard.html
{% extends "base.html" %}
{% block title %}Shipping App{% endblock title %}

{%- block page_content %}

<div class="container page-header">
    <section class="hero is-dark mb-5">
        <div class="hero-body">
            <p class="title">Hero title</p>
            <p class="subtitle">Hero subtitle</p>
        </div>
    </section>
</div>
<div class="container">
    <div class="columns is-centered">
        <div class="panel column is-4">
            <p class="panel-heading">
                <span class="panel-icon has-text-info">
                    <i class="fa-solid fa-truck-fast"></i>
                </span>
                <span>Most Recent Orders</span>
            </p>
            {%- for item in invoices %}
            <div class="panel-block">
                <div class="notification is-success" id="invoicenotify">
                    <button class="delete"></button>
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <p class="title is-4">{{ item["Purchaser"] }}</p>
                                <p class="subtitle is-6">{{ item["Invoice #"] }} {{ item["Ordered on"] }}</p>
                            </div>
                        </div>
                        <div class="content">
                            <time datetime="2016-1-1">{{ item["Ordered on"] }}</time>
                            <a class="panel-block is-active">
                                <span class="panel-icon">
                                    <i class="fas fa-book" aria-hidden="true"></i>
                                </span>
                                {{ item["Item"] }}
                            </a>
                            <a class="panel-block">
                                <span class="panel-icon">
                                    <i class="fas fa-book" aria-hidden="true"></i>
                                </span>
                                {{ item["Amount"] }} at {{ item["Cost"] }}
                            </a>
                            <a class="panel-block">
                                <span class="panel-icon">
                                    <i class="fas fa-book" aria-hidden="true"></i>
                                </span>
                                {{ item["Notes"] }}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor-%}
        </div>
        <div class="panel column is-8 is-offset-1">
            <p class="panel-heading">
                <span class="panel-icon">
                    <i class="fa-solid fa-truck-fast"></i>
                </span>
                <span>Tracking Map</span>
            </p>
            <div class="panel-block">
                <div id='dashtrack' class='chart'></div>

            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    const locdata = {{ coords| tojson | safe }};

    const info = [{
        type: 'scattergeo',
        mode: 'markers',
        lon: locdata.map(loc => loc.port_longitude),
        lat: locdata.map(loc => loc.port_lattitude),
        marker: {
            size: 8,
            color: 'blue'
        },
        text: locdata.map(loc => `${loc.port_city},${loc.port_country}`)
    }];

    const layout = {
        hovermove: 'closest',
        scope: 'world',
        geo: {
            projection: {
                type: 'mercator'
            },
        },
        title: 'Some of our servicing locations'
    };
    Plotly.newPlot('dashtrack', info, layout);
</script>
{% endblock page_content -%}

templates/db_page.html
{% extends "base.html" %}
{% block title %}DB Query{% endblock %}
{% block page_content %}
<div class="page-header">
    <h1>Database Query</h1>
</div>
<div>
    {{ results|safe }}
</div>

{% endblock %}

templates/employees.html
{% extends "base.html" %}
{% block title %}Demo Flask{% endblock %}
{% block page_content %}
<div class="page-header mb-2">
    <h1>Employee Search</h1>
</div>
<div class="container columns is-centered">
    <div class="column is-half">
        <div class="panel is-4" id="employee">
            <p class="panel-heading mb-2">Employee Lookup</p>
            <form class="field is-grouped has-addons has-addons-centered" action="{{ url_for('main.employees') }}" method="get">
                <div class="control is-expanded px-2">
                    <input type="text" class="input is-small is-info" name="employee" id="employee-results">
                </div>
                <div class="control px-2 pb-2">
                    <button type="submit" class="button is-info">Search</button>
                </div>
            </form>
            <div id="employeecard" class="px-2 pb-2"></div>
        </div>
    </div>
</div>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}Shipping Dash{% endblock %}

{% block page_content %}
<div class="container page-header">
    <section class="hero is-dark mb-5">
        <div class="hero-body">
            <figure class="image is-centered is-64x64">
                <img src="{{ url_for('static',filename='logo.png') }}" alt="">
            </figure>
            <p class="title">Welcome to AltaVista Manufacturing</p>
            <p class="subtitle">Where the most important thing is end to end</p>
        </div>
    </section>
</div>
<div class="columns is-centered">
    <div class="column is-centered is-4">
        <div class="card  is-dark">
            <div class="card-image">
                <figure class="image is-64x128">
                    <img src="{{ url_for('static',filename='boat1.jpeg') }}" alt="" />
                </figure>
            </div>
            <div class="content">
                Keep track of all pending shipments
                <span class="panel-icon has-text-info">
                    <i class="fa-solid fa-truck-fast"></i>
                </span>
            </div>
        </div>
    </div>
    <div class="column is-centered is-4">
        <div class="card is-dark">
            <div class="card-image">
                <figure class="image is-64x128">
                    <img src="{{ url_for('static',filename='boat2.jpeg') }}" alt="" />
                </figure>
            </div>
            <div class="content">
                Keep track of all pending orders
                <span class="panel-icon has-text-info">
                    <i class="fa-solid fa-clipboard"></i>
                </span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/reports.html
{% extends "base.html" %}
{% block title %}Request A Quote{% endblock %}


{% block page_content %}

<h1>View Charts</h1>
<div id='chart' class='chart'></div>
<div class="columns is-centered">
    <div class="column is-centered is-4">
        <div class="card  is-dark">
            <div class="card-image">
                <figure class="image is-64x128">
                    <img src="{{ url_for('static',filename='boat1.jpeg') }}" alt="" />
                </figure>
            </div>
            <div class="content">
                Keep track of all pending shipments
                <span class="panel-icon has-text-info">
                    <i class="fa-solid fa-truck-fast"></i>
                </span>
            </div>
        </div>
    </div>
    <div class="column is-centered is-4">
        <div class="card is-dark">
            <div class="card-image">
                <figure class="image is-64x128">
                    <img src="{{ url_for('static',filename='boat2.jpeg') }}" alt="" />
                </figure>
            </div>
            <div class="content">
                Keep track of all pending orders
                <span class="panel-icon has-text-info">
                    <i class="fa-solid fa-clipboard"></i>
                </span>
            </div>
        </div>
    </div>
</div>

<script type='text/javascript'>
    var graphs = {{ graphJSON | safe}};
    Plotly.plot('chart', graphs, {});
</script>
{% endblock %}

templates/search.html
{% extends "base.html" %}
{% block title %}Demo Flask{% endblock %}
{% block page_content %}
<div class="page-header mb-2">
    <h1>Search</h1>
</div>
<div class="container columns is-centered">
    <div class="column is-half">
        <div class="panel is-4" id="tracking">
            <p class="panel-heading mb-2">Tracking Number Lookup</p>
            <form class="field is-grouped has-addons has-addons-centered" action="{{ url_for('main.tracking_search') }}" method="get">
                <div class="control is-expanded px-2">
                    <input type="text" class="input is-small is-info" name="tracking" id="tracking-results">
                </div>
                <div class="control px-2 pb-2">
                    <button type="submit" class="button is-info">Search</button>
                </div>
            </form>
            <div id="trackingcard" class="px-2 pb-2"></div>
            <div id="trackingDiv" class="px-2 pb-2"></div>
        </div>
    </div>
    <div class="column is-half">
        <div class="panel is-4" id="invoice">
            <p class="panel-heading mb-2">Invoice Lookup</p>
            <form class="field is-grouped has-addons has-addons-centered" action="{{ url_for('main.invoice_search') }}" method="get">
                <div class="control is-expanded px-2">
                    <input type="text" class="input is-small is-info" name="invoice" id="invoice-results">
                </div>
                <div class="control px-2 pb-2">
                    <button type="submit" class="button is-info">Search</button>
                </div>
            </form>
            <div id="invoicecard" class="px-2 pb-2"></div>
            <div id="invoiceDiv" class="px-2 pb-2"></div>
        </div>
    </div>
</div>

{% endblock %}